server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mvc:
    servlet:
      path: /api/v1/user

security:
  jwt:
    secret: ${JWT_SECRET:VerySecretKeyThatShouldBeLongEnoughChangeMe}
    expiration-ms: 3600000 # 1 hour
# Logging
logging:
  level:
    com.nextepisode.tmdbservice: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.apache.coyote.http11: DEBUG
    org.hibernate.SQL: DEBUG

