server:
  port: ${SERVER_PORT:8080}


security:
  jwt:
    secret: ${JWT_SECRET:VerySecretKeyThatShouldBeLongEnoughChangeMe}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}


spring:
  application:
    name: api-gateway


  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=X-Forwarded-Host
      routes:
        - id: auth
          uri: http://auth-service:8080
          predicates:
            - Path=/api/v1/auth/**

        - id: tmdb
          uri: http://tmdb-service:8080
          predicates:
            - Path=/api/v1/tmdb/**

        - id: user
          uri: http://user-service:8080
          predicates:
            - Path=/api/v1/user/**



