server:
  port: 8081

spring:
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=X-Forwarded-Host
      routes:
        - id: auth
          uri: http://auth-service:8080
          predicates:
            - Path=/auth/**

        - id: tmdb
          uri: http://tmdb-service:8083
          predicates:
            - Path=/api/v1/tmdb/**




jwt:
  # default if not set via env
  secret: "${JWT_SECRET:VerySecretKeyThatShouldBeLongEnoughChangeMe}"
