server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: tmdb-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tmdbdb}
    username: ${SPRING_DATASOURCE_USERNAME:tmdbdbuser}
    password: ${SPRING_DATASOURCE_PASSWORD:tmdbdbpass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mvc:
    servlet:
      path: /api/v1/tmdb

tmdb:
  api:
    token: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI4MDgxNTY1ZmE5MGMwMzBkYWNhZmQ4YmM3MjQwODg0ZiIsIm5iZiI6MTY3NjY2NDQ4Ny4yOTYsInN1YiI6IjYzZWZkZWE3Y2FhY2EyMDBhMTlhNjU1NyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.5Lbprj-n6HfFkNN6euM9luzi9DUYuafyPJTP3Wy-xgw"
    key: ${TMDB_API_KEY:8081565fa90c030dacafd8bc7240884f}
    base-url: https://api.themoviedb.org/3
    image-base-url: https://image.tmdb.org/t/p
    timeout: 5000
  cache:
    ttl-days: 7



security:
  jwt:
    secret: ${JWT_SECRET:VerySecretKeyThatShouldBeLongEnoughChangeMe}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}



logging:
  level:
    com.nextepisode: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG